services:
  drupal:
    container_name: drupal
    image: drupal:10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/opt/drupal
    depends_on:
      - mysql
    environment:
      DRUPAL_DATABASE_HOST: ${MYSQL_HOST}
      DRUPAL_DATABASE: ${MYSQL_DATABASE}
      DRUPAL_DATABASE_USERNAME: ${MYSQL_USER}
      DRUPAL_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

volumes:
  db_data:
